---
apiVersion: v1
kind: Service
metadata:
  name: dolphindb-{{ .Values.userId }}
  labels:
    app: dolphindb-{{ .Values.userId }}
    userId: {{ .Values.userId }}
spec:
  type: ClusterIP
  selector:
    app: dolphindb-{{ .Values.userId }}
  ports:
    - name: api
      port: {{ .Values.dolphindb.port }}
      targetPort: {{ .Values.dolphindb.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dolphindb-{{ .Values.userId }}
  labels:
    app: dolphindb-{{ .Values.userId }}
    userId: {{ .Values.userId }}
spec:
  serviceName: dolphindb-{{ .Values.userId }}
  replicas: 1
  selector:
    matchLabels:
      app: dolphindb-{{ .Values.userId }}
  template:
    metadata:
      labels:
        app: dolphindb-{{ .Values.userId }}
        userId: {{ .Values.userId }}
    spec:
      containers:
      - name: dolphindb
        image: {{ .Values.dolphindb.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.dolphindb.port }}
        env:
        - name: DDB_USER
          value: {{ .Values.dolphindb.username | quote }}
        - name: DDB_PASS
          value: {{ .Values.dolphindb.password | quote }}
        volumeMounts:
        - name: dolphindb-data
          mountPath: /opt/dolphindb/data
        resources:
          {{- toYaml .Values.resources.dolphindb | nindent 10 }}
  volumeClaimTemplates:
  - metadata:
      name: dolphindb-data
    spec:
      storageClassName: {{ .Values.dolphindb.storageClass }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.dolphindb.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-{{ .Values.userId }}
  labels:
    app: codeserver-{{ .Values.userId }}
    userId: {{ .Values.userId }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver-{{ .Values.userId }}
  template:
    metadata:
      labels:
        app: codeserver-{{ .Values.userId }}
        userId: {{ .Values.userId }}
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-settings
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              mkdir -p /config
              cat > /config/settings.json <<SETTINGSEOF
              {
                "dolphindb.connections": [
                  {
                    "name": "localDDB",
                    "url": "ws://dolphindb-{{ .Values.userId }}:{{ .Values.dolphindb.port }}",
                    "autologin": true,
                    "username": "{{ .Values.dolphindb.username }}",
                    "password": "{{ .Values.dolphindb.password }}"
                  }
                ],
                "extensions.autoUpdate": false,
                "extensions.autoCheckUpdates": false,
                "telemetry.telemetryLevel": "off",
                "workbench.enableExperiments": false
              }
              SETTINGSEOF
          volumeMounts:
            - name: config-volume
              mountPath: /config
        - name: fix-perms
          image: {{ .Values.codeserver.image }}
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              uid=$(awk -F: '/^coder:/{print $3; exit}' /etc/passwd 2>/dev/null || echo 0)
              gid=$(awk -F: '/^coder:/{print $4; exit}' /etc/passwd 2>/dev/null || echo 0)
              if [ -f /config/settings.json ]; then
                chown ${uid}:${gid} /config/settings.json 2>/dev/null || true
                chmod 0644 /config/settings.json 2>/dev/null || true
              fi
          volumeMounts:
            - name: config-volume
              mountPath: /config
      containers:
      - name: code-server
        image: {{ .Values.codeserver.image }}
        imagePullPolicy: IfNotPresent
        env:
          - name: PASSWORD
            value: {{ .Values.codeserver.password | quote }}
        ports:
          - containerPort: {{ .Values.codeserver.port }}
        volumeMounts:
          - name: config-volume
            mountPath: /home/coder/.local/share/code-server/Machine/settings.json
            subPath: settings.json
        resources:
          {{- toYaml .Values.resources.codeserver | nindent 10 }}
      volumes:
      - name: config-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-{{ .Values.userId }}
  labels:
    app: codeserver-{{ .Values.userId }}
    userId: {{ .Values.userId }}
spec:
  type: NodePort
  selector:
    app: codeserver-{{ .Values.userId }}
  ports:
    - port: {{ .Values.codeserver.port }}
      targetPort: {{ .Values.codeserver.port }}
